channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.0.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==5.9.8
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
